### ISSUE TITLE
SPIKE: Determine work involved for automatic display of Emory Emergency notices via CEPAR on Emory Libraries sites

### ISSUE THREAD

**Issue by cwbragg** [emory-libraries/web-enhance#30] opened 2023-02-03 19:14 UTC
The details of the enhancement request are included below. Because it was initially determined the work involved to implement this would be beyond one sprint, I am turning this into a Spike ticket to develop a plan for all tasks needed to implement this. @maxdmayhew - I will schedule a brief meeting for you and I to discuss how we should document this.

**Is your feature request related to new functionality not yet included in the product? Please describe.**
New, this would automatically appear at the top of Emory Libraries sites when an emergency occurs

**Is your feature request related to a problem or a change to existing functionality? Please describe.**
A change - staff now "manually" add emergency notice banners to the sites.

**Describe the solution you'd like**
When an emergency notice is published by CEPAR on the Emory University site, it would also automatically appear in a banner at the top of the Emory Libraries and Oxford sites. 

This functionality was available in the past (in Cascade). John Mills (Emory online communications) thinks that this will be possible in Drupal as well. 

**Describe alternatives you've considered**
Staff continue to manually add banners to the sites, which requires coordination and keeping up with CEPAR email notices.  

**How will this impact users?**
Patrons and library will have a greater chance of getting emergency information in a timely manner.

**Additional context**

**Comment by maxdmayhew** [comment] 2023-11-02 14:07
FEEDS / XML setup similar to: https://app.zenhub.com/workspaces/library-website-6176fec507eb0000126ee8e1/issues/gh/emory-libraries/web-enhance/21

**Comment by CB987** [comment] 2023-11-08 00:22
can we get a link to where it was set up in cascade previously? or if not, is john mills the best person to communicate with to get the info?

**Comment by maxdmayhew** [comment] 2023-11-20 15:34
@cwbragg still need CEPAR link to test out creating a feed for it.

**Comment by cwbragg** [comment] 2023-11-30 15:20
@maxdmayhew I've sent an email to John Mills, and will follow up next week if I don't hear back soon.

**Comment by cwbragg** [comment] 2023-11-30 17:43
From Jennifer Etheredge:

You’re welcome to tackle this however you like and write your own dynamic call and JavaScript to get the RAVE RSS. But I’m including what we’ve done and you’re welcome to use this solution.
 
The RSS URL from RAVE is this:
 
[https://www.getrave.com/rss/emory/channel1](https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.getrave.com%2Frss%2Femory%2Fchannel1&data=05%7C01%7Ccbragg%40emory.edu%7C3e15623747794fe025cd08dbf1bdc5d1%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C638369569601071392%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=U9qXM3GZaQdO6DMbl8kgfs5jSLpm37sMRfTC%2BYucuE8%3D&reserved=0)
 
A test RSS feed is [https://www.getrave.com/rss/emory/channel3](https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.getrave.com%2Frss%2Femory%2Fchannel3&data=05%7C01%7Ccbragg%40emory.edu%7C3e15623747794fe025cd08dbf1bdc5d1%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C638369569601071392%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=gNxSXJXSJRwGSVxjPEyn7AJ%2BYzJnSvo1%2FY3bqsmqKpc%3D&reserved=0)
 
We have production PHP that echos some HTML if it’s not “all clear” here:
https://template.aws.emory.edu/shared-assets/emergency/alert-feed.php
 
 
And a test PHP to always return data here for the purposes of developing:
https://template.aws.emory.edu/shared-assets/emergency/alert-feed-dev.php
 
That can be used to write some AJAX or a fetch in JavaScript to add it under the header of a site in a <div> with an ID.
 
Our JavaScript is this:
 
//Emergency Announcement
                const emergencyAnnouncementSetup = function () {
                                const pollInterval = 60000;
                                const feedURL = 'https://template.aws.emory.edu/shared-assets/emergency/alert-feed.php';
                                const elementID = 'emerg-alert-system';
                                const pollFn = function () {
                                                $.ajax({
                                                                url: feedURL,
                                                                cache: false,
                                                                success: function (data) {
                                                                                const alert = data.toString().trim().length === 0 ? false : true;
                                                                                const emergencyElement = $("#" + elementID);
                                                                                emergencyElement.empty();
                                                                                if (alert) {
                                                                                                emergencyElement.append(
                                                                                                                '<div class="alert alert-danger alert-dismissible fade show" role="alert">' +
                                                                                                                data.toString().replace(/<[^>]+>/g, '') +
                                                                                                                '<button type="button" class="close" data-dismiss="alert" aria-label="Close">' +
                                                                                                                '<span aria-hidden="true">&times;</span>' +
                                                                                                                '</button>' +
                                                                                                                '</div>'
                                                                                                );
                                                                                }
                                                                }
                                                });
                                }
                                if(!$('#' + elementID).length){
                                    $siteHeader.append('<div id="' + elementID + '"></div>');
                                }
                                setTimeout(pollFn, pollInterval);
                                pollFn();
                };
 
Best,
Jennifer

**Comment by CB987** [comment] 2023-12-01 22:11
@cwbragg do we want this to be an alert or a notification (ie, dismissable)?

**Comment by CB987** [comment] 2023-12-02 00:11
<img width="1172" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnNvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fb4743dd977ecb34872d22eabab998ac26943c24/Screenshot%202023-12-01%20at%207.11.45%E2%80%AFPM.png" alt="Screenshot 2023-12-01 at 7.11.45 PM.png" />

**Comment by CB987** [comment] 2023-12-04 19:06
@cwbragg could you please ask Jennifer for a handful of examples of messages? Right now I have it filtering out anything that contains "all clear" but Max realized there's a good chance that an emergency message could also contain those words, as the test message also does. 
Thanks!

**Comment by CB987** [comment] 2023-12-04 21:01
after much testing, i currently have it filtering out on the exact title "ALL CLEAR: RSS" which then prevents it from publishing because it can't publish without a title. 
So here is a screenshot of a test manually added site notification and the test cepar notification, which has the title "LITS: RSS Test All Clear" 
<img width="642" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmt1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--62ed8c693b5124c61c9f9797edbcc259ece65d09/Screenshot%202023-12-04%20at%204.01.34%E2%80%AFPM.png" alt="Screenshot 2023-12-04 at 4.01.34 PM.png" />

**Comment by CB987** [comment] 2023-12-04 23:35
have deployed the cepar branch to dev. the feeds have to be created initially as they are content. i created both the production and test channels. channel 1 import failed as designed and not be created, because it is an all clear. channel 3 import caused the test notification to be published and appear as a banner on the site. i'm going to see how this performs running on cron and if there are any errors, but otherwise the only way to test is if we do get an emergency alert through the feed.

**Comment by CB987** [comment] 2023-12-07 16:21
<img width="578" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEJBQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--59c196e8e665dc597b669c56e2835ae68170b6c9/Screenshot%202023-12-07%20at%2011.19.26%E2%80%AFAM.png" alt="Screenshot 2023-12-07 at 11.19.26 AM.png" />
the content items will only create (and publish) a new item when the existing item changes.

**Comment by CB987** [comment] 2023-12-07 16:22
PR #[878](https://github.com/emory-libraries/d9-emory-libraries/pull/878)

**Comment by lovinscari** [comment] 2023-12-13 16:41
@cwbragg - I am not sure if it is possible to coordinate a test of this? If not, I would say review the screenshots provided by Clare and we can always open a bug ticket if we find the automation is not working as expected.

**Comment by cwbragg** [comment] 2023-12-13 20:58
@CB987 the screenshots appear as broken links here. Clare, I've sent a Slack msg to you.

**Comment by cwbragg** [comment] 2023-12-13 21:05
@CB987 @lovinscari Clare shared the screenshots of the banner with me. It displayed the test of the CEPAR system. I think it's ready for prod.

**Comment by cwbragg** [comment] 2024-01-10 21:45
@CB987 Ready for deploy to satge

**Comment by lovinscari** [comment] 2024-08-15 15:37
The issue that was experienced the last time was the errors and formatting we ran into when deploying to production, specifically for Oxford's home page. It was determined at that point to push this back and review it during a time we could investigate why this was happening when moving to production.

**Comment by maxdmayhew** [comment] 2024-08-19 12:44
basic working example of the CEPAR banner. I have two questions (for now):
- Do we want a more "alert" look and feel that is specific to the CEPAR alert system? You can see the two existing notifications that editors can use currently in the picture I added. Since this is for emergencies I am a little concerned about using one of the existing color ways and users not noticing the emergency alert system message. If this is not a concern which color way would you like me to use?
- You can also see in the picture notifications have a label and I have set the CEPAR alert label as "CEPAR EMERGENCY ALERT". What would you like me to set that to? I can also just remove it.

<img width="1763" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVJwQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ce7a814aed184d8978aa7ac11a7893653b86a79e/image.png" alt="image.png" />

**Comment by lovinscari** [comment] 2024-08-19 15:23
@maxdmayhew - thank you for your work on this in such a short period of time! I believe having the CEPAR alert in red with the same style as the other alerts is fine. However, I would change the wording to Emory University Emergency Alert as opposed to CEPAR as I am not certain everyone will know what that means. I believe @cwbragg will not be available to comment with his thoughts until Friday. Once you believe this is ready for testing on production, let me know and I will coordinate with the Content Czars as we will want to complete our testing before the semester begins.

**Comment by maxdmayhew** [comment] 2024-08-19 15:33
This is great thank you @maxdmayhew 
I have a bit of work ahead of me to get this ready to merge to dev but I will add my PR ASAP.

Thank you!

**Comment by cwbragg** [comment] 2024-08-22 01:46
@maxdmayhew @lovinscari Hi all! I'll send this to Shannon tomorrow morning for his thoughts.

**Comment by cwbragg** [comment] 2024-08-23 15:15
@maxdmayhew @lovinscari Shannon agrees with the red banner color for campus-wide emergencies and renaming the banner. He suggests changing the wording to "EMORY EMERGENCY ALERT"

**Comment by maxdmayhew** [comment] 2024-08-23 15:19
<img width="273" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3FDQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--166e0e21f6a8a0607399cb5173458f78a6045f1d/image.png" alt="image.png" />

based on conversation with Collin Brittle, the script is setup to ping every 1 minute. You can see this in the screenshot above. Ignore the referrer policy. It is an IDE setup issue.

**Comment by maxdmayhew** [comment] 2024-08-23 15:25
<img width="1173" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1NEQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--52f2e368109a1b46c904313616509bcb8ca20b31/Screenshot%202024-08-23%20at%2011.23.39%E2%80%AFAM.png" alt="Screenshot 2024-08-23 at 11.23.39 AM.png" />

Cari had me make that change a few days ago but good looking out! Thank you @cwbragg

**Comment by maxdmayhew** [comment] 2024-08-23 15:26
PR: https://github.com/emory-libraries/d9-emory-libraries/pull/954

**Comment by cwbragg** [comment] 2024-08-23 15:35
Oh! To clarify Shannon's suggestion, he suggested "EMORY EMERGENCY ALERT" rather than the longer "Emory University Emergency Alert", as anyone seeing the alert knows they’re in the Emory University ecosystem.

Just wanted to get that on the record.

**Comment by lovinscari** [comment] 2024-08-26 13:47
I'm okay with Shannon's suggestion.

**Comment by maxdmayhew** [comment] 2024-08-26 14:03
PR for label update: https://github.com/emory-libraries/d9-emory-libraries/pull/955

**Comment by cwbragg** [comment] 2024-08-30 17:31
@maxdmayhew Since Cari is in agreement, we can change the label to EMORY EMERGENCY ALERT". Other than that, is this good to go? Thanks!

**Comment by cwbragg** [comment] 2024-08-30 20:21
@maxdmayhew Since everyone is in agreement, we can modify the label to read "EMORY EMERGENCY ALERT" and then we should be done with this ticket!

**Comment by maxdmayhew** [comment] 2024-08-31 17:08
Yep! This was finished in the label update PR above!

**Closed** 2024-11-06 20:15 UTC
Labels: enhancement, Acquia PS, Acquia Engagement 2023
